export const EVENT_REQUEST = "EVENT_REQUEST"
export const EVENT_SUCCESS = "EVENT_SUCCESS"
export const EVENT_FAILURE = "EVENT_FAILURE"

export const FAVORITE_EVENT_REQUEST = "FAVORITE_EVENT_REQUEST"
export const FAVORITE_EVENT_SUCCESS = "FAVORITE_EVENT_SUCCESS"
export const FAVORITE_EVENT_FAILURE = "FAVORITE_EVENT_FAILURE"