export const GET_EVENT_CATEGORIES_REQUEST = "GET_EVENT_CATEGORIES_REQUEST";
export const GET_EVENT_CATEGORIES_SUCCESS = "GET_EVENT_CATEGORIES_SUCCESS";
export const GET_EVENT_CATEGORIES_FAILURE = "GET_EVENT_CATEGORIES_FAILURE";